name = "account"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SESSIONS"
id = "5c6e3465296c41e986c086727c8459e7"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "gokkehub-avatars"

[vars]
COOKIE_DOMAIN = ".gokkehub.com"
