name = "timelinedrop"
pages_build_output_dir = "dist"
compatibility_date = "2024-10-22"

[[kv_namespaces]]
binding = "SESSIONS"
id = "5c6e3465296c41e986c086727c8459e7"

[vars]
COOKIE_DOMAIN      = ".gokkehub.com"
SUPABASE_URL       = "https://verbxfbfurachhxztkob.supabase.co"
# SUPABASE_SERVICE_ROLE_KEY, SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET set as encrypted secrets
