// ── Spotify ───────────────────────────────────────────────────────────────────

export interface SpotifyTrack {
  id:          string;
  name:        string;
  artist:      string;
  albumName:   string;
  releaseYear: number;
  coverUrl:    string;
  uri:         string; // spotify:track:ID — required for Web Playback SDK
}

// ── Database rows ─────────────────────────────────────────────────────────────

export type LateJoinMode = "open" | "spectator-only" | "closed";

export type JudgeMode =
  | "team-captain"
  | "next-team-captain"
  | "host"
  | "vote-all";

export type Difficulty = "easy" | "medium" | "hard" | "hardest";
export type PlaylistMode = "as-is" | "inspiration" | "smart-filter";

// Where the round's songs come from. Group taste runs the curation engine
// against each player's Last.fm history; playlist uses tracks the host pasted
// from a Spotify playlist URL.
export type SongSource = "group-taste" | "playlist";

export interface TlRoomSettings {
  lateJoinMode?:       LateJoinMode;
  streamerMode?:       boolean;
  hideSpectators?:     boolean;
  teamSwapEnabled?:    boolean;
  judgeMode?:          JudgeMode;
  voteTimerSeconds?:   number;
  difficulty?:         Difficulty;
  /** @deprecated kept for back-compat — UI no longer surfaces this. */
  playlistMode?:       PlaylistMode;
  skipRecentlyHeard?:  boolean;       // 14-day blacklist toggle
  singleScreenMode?:   boolean;       // host plays for every team on one device
  songSource?:         SongSource;    // group-taste (default) | playlist
}

export const DEFAULT_TL_SETTINGS: Required<TlRoomSettings> = {
  lateJoinMode:      "open",
  streamerMode:      false,
  hideSpectators:    false,
  teamSwapEnabled:   false,
  judgeMode:         "team-captain",
  voteTimerSeconds:  20,
  difficulty:        "medium",
  playlistMode:      "as-is",
  skipRecentlyHeard: true,
  singleScreenMode:  false,
  songSource:        "group-taste",
};

export interface TlRoom {
  id:               string;       // 6-char code
  host_id:          string;
  status:           "lobby" | "playing" | "finished";
  win_target:       number;
  active_team_id:   number | null;
  track_pool:       SpotifyTrack[];
  track_cursor:     number;
  current_round_id: number | null;
  playing_since:    number | null; // epoch ms when Web Playback SDK started
  paused_at_ms:     number | null; // ms offset in track when paused
  settings:         TlRoomSettings;
  created_at:       string;
}

export interface TlTeam {
  id:             number;
  room_id:        string;
  name:           string;
  tokens:         number;            // ready-to-use tokens
  tokens_pending: number;            // earned this turn; promote to tokens when team's next turn begins
  pending_tracks: SpotifyTrack[];    // cards earned this turn, not yet locked
  sort_order:     number;
}

export interface TlPlayer {
  id:               string;
  room_id:          string;
  team_id:          number | null;
  name:             string;
  is_captain:       boolean;
  is_host:          boolean;
  is_spectator:     boolean;
  discord_id:       string | null;
  lastfm_username:  string | null;
  manual_artists:   string[];      // fallback when no Last.fm
  joined_at:        string;
}

export type Confidence = "known" | "likely" | "stretch" | "wild";

export interface TlTeamToken {
  id:             number;
  room_id:        string;
  team_id:        number;
  type:           string;       // TokenType from lib/tokens.ts
  granted_at:     string;
  granted_round:  number | null;
  used_at:        string | null;
  used_round:     number | null;
  pending:        boolean;      // earned this turn, ready when team plays next
}

export interface TlRound {
  id:                  number;
  room_id:             string;
  team_id:             number;
  track:               SpotifyTrack;
  left_year:           number | null;
  right_year:          number | null;
  staged_left_year:    number | null;
  staged_right_year:   number | null;
  outcome:             "correct" | "incorrect" | null;
  // Token-state flags (migration 009)
  skipped:             boolean;
  cover_revealed:      boolean;
  year_tolerance:      number;
  more_or_less_card_id: string | null;
  recovery_armed:      boolean;
  artist_guess:        string | null;
  songname_guess:      string | null;
  artist_correct:      boolean | null;
  songname_correct:    boolean | null;
  artist_votes:        Record<string, boolean>;
  songname_votes:      Record<string, boolean>;
  judging_started_at:  string | null;
  judging_finalized:   boolean;
  bonus_awarded:       boolean;
  revealed_at:         string | null;
  // Curation enrichment (populated when track was generated by the curation engine)
  familiarity_score:   number | null;
  confidence:          Confidence | null;
  players_who_know_it: string[];   // discord ids
  lastfm_name:         string | null;
  artist_name:         string | null;
  // Year correction flow (any player can propose; host approves; on approval
  // corrected_year overrides track.releaseYear for placement & timeline)
  corrected_year:                 number | null;
  year_correction_proposed:       number | null;
  year_correction_proposed_by:    string | null;
  year_correction_proposed_name:  string | null;
}

export interface StageRequest {
  round_id:          number;
  player_id:         string;
  staged_left_year:  number | null;
  staged_right_year: number | null;
}

export interface TlTimelineEntry {
  team_id:        number;
  track_id:       string;
  year:           number;             // year used for ordering — Spotify default or corrected
  position:       number;
  track:          SpotifyTrack;
  corrected_year: number | null;      // host-approved correction, if any
}

export interface TlPing {
  id:          number;
  round_id:    number;
  player_id:   string;
  player_name: string;
  year:        number;
  created_at:  string;
}

export interface TlNote {
  id:          number;
  round_id:    number;
  player_id:   string;
  player_name: string;
  content:     string;
  created_at:  string;
}

// ── Aggregated game state (built client-side from subscriptions) ──────────────

export interface GameState {
  room:         TlRoom;
  teams:        TlTeam[];
  players:      TlPlayer[];
  round:        TlRound | null;
  timelines:    Record<number, TlTimelineEntry[]>; // teamId → sorted entries
  notes:        TlNote[];
  pings:        TlPing[];
  tokens:       Record<number, TlTeamToken[]>; // teamId → tokens (granted, not yet used)
  myPlayer:     TlPlayer | null;
}

// ── WebRTC signaling messages (sent via Supabase Broadcast) ──────────────────

export type WrtcMessage =
  | { type: "want-audio";  from: string }
  | { type: "offer";       from: string; to: string; sdp: RTCSessionDescriptionInit }
  | { type: "answer";      from: string; to: string; sdp: RTCSessionDescriptionInit }
  | { type: "ice";         from: string; to: string; candidate: RTCIceCandidateInit }
  | { type: "audio-ready" }
  | { type: "audio-gone"  };

// ── Session (from account.gokkehub.com) ──────────────────────────────────────

export interface GokkeHubSession {
  userId:          string;
  displayName:     string | null;
  email:           string | null;
  avatarUrl:       string | null;
  lastfmUsername?: string | null;
  spotify?: {
    id:           string;
    accessToken:  string;
    refreshToken: string;
    expiresAt:    number;
    displayName:  string | null;
  } | null;
  discord?: {
    id: string;
  } | null;
}

// ── Function request/response shapes ─────────────────────────────────────────

export interface CreateRoomRequest {
  name:          string; // host's display name if not logged in
  win_target:    number;
  team_names:    string[];
  host_team?:    number | null; // 0-based index into team_names; null/undefined → DJ-only spectator
  is_spectator?: boolean;       // host joins as DJ-only spectator
  settings?:     TlRoomSettings;
}

export interface CreateRoomResponse {
  room_id:   string;
  player_id: string;
}

export interface JoinRoomRequest {
  name:          string;
  team_id?:      number | null;
  is_spectator?: boolean;
}

export interface JoinRoomResponse {
  player_id:    string;
  team_id:      number | null;
  is_spectator: boolean;
}

export interface UpdateSettingsRequest {
  player_id: string;
  settings:  TlRoomSettings;
}

export interface KickPlayerRequest {
  player_id: string; // host's id
  target_id: string; // player to kick
}

export interface ChangeTeamRequest {
  player_id: string; // caller (and target — players move themselves)
  team_id:   number | null; // null → spectator
}

export interface AddPlaylistRequest {
  url: string;
}

export interface AddPlaylistResponse {
  added:  number;
  total:  number;
  name:   string;
}

export interface PlacementRequest {
  round_id:        number;
  left_year:       number | null;
  right_year:      number | null;
  artist_guess?:   string;  // optional; provided when captain confirms guess together with placement
  songname_guess?: string;
}

export interface PlacementResponse {
  outcome:    "correct" | "incorrect";
  actual_year: number;
}

export interface TurnActionRequest {
  action: "stop" | "token" | "next";
}

export interface GuessRequest {
  round_id:        number;
  player_id:       string;
  artist_guess:    string;
  songname_guess:  string;
}

export interface JudgeRequest {
  round_id:  number;
  player_id: string;
  kind:      "artist" | "songname" | "combined";
  verdict:   boolean;
}

export interface ProposeYearCorrectionRequest {
  round_id:  number;
  player_id: string;
  year:      number;
}

export interface ApproveYearCorrectionRequest {
  round_id:  number;
  player_id: string;     // host
  approve:   boolean;
}

export interface DismissPingRequest {
  ping_id:   number;
  player_id: string;     // captain or host
}

export interface FinalizeJudgmentRequest {
  round_id:  number;
  player_id: string;  // any player can request finalize after timer
}

export interface UseTokenRequest {
  round_id:  number;
  player_id: string;  // captain only
}
